### ISSUE TITLE
Button Text not visible.

### ISSUE THREAD

**Issue by ArchishmanSengupta** [praveenscience/easya-website#31] opened 2021-05-27 14:56 UTC
In landing page, 
the class Action-button's text to #how-it-works page is not visible. 
Reference: 
![is](https://user-images.githubusercontent.com/71402528/119848827-c1bebf80-bf29-11eb-80ca-679fd25db064.png)

Can you assign me this? 
Thank you

**Comment by praveenscience** [comment] 2021-05-27 14:58
Wasn't this already been raised?

**Comment by praveenscience** [comment] 2021-05-27 14:58
Dupe of #16!

**Closed by praveenscience** 2021-05-27 14:58 UTC
